---
- name: Install apt nut related packages
  apt: 
    name:
      - nut
      - nut-client
      - nut-server
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Check if original ups.conf has been saved
  stat:
    path: /etc/nut/ups.conf.orig
  register: check_ups_conf

- name: Backup original ups.conf
  ansible.builtin.copy:
    src: /etc/nut/ups.conf
    dest: /etc/nut/ups.conf.orig
    remote_src: yes
    mode: '0644'
  when: not check_ups_conf.stat.exists
  become: yes

- name: Template to /etc/nut/ups.conf
  ansible.builtin.template:
    src: templates/ups.conf.j2
    dest: /etc/nut/ups.conf
    mode: '0644'
  become: yes

- name: Check if original upsmon.conf has been saved
  stat:
    path: /etc/nut/upsmon.conf.orig
  register: check_upsmon_conf

- name: Backup original upsmon.conf
  ansible.builtin.copy:
    src: /etc/nut/upsmon.conf
    dest: /etc/nut/upsmon.conf.orig
    remote_src: yes
    mode: '0644'
  when: not check_upsmon_conf.stat.exists
  become: yes

- name: Template to /etc/nut/upsmon.conf
  ansible.builtin.template:
    src: templates/upsmon.conf.j2
    dest: /etc/nut/upsmon.conf
    mode: '0644'
  become: yes

- name: Check if original upsd.conf has been saved
  stat:
    path: /etc/nut/upsd.conf.orig
  register: check_upsd_conf

- name: Backup original upsd.conf
  ansible.builtin.copy:
    src: /etc/nut/upsd.conf
    dest: /etc/nut/upsd.conf.orig
    remote_src: yes
    mode: '0644'
  when: not check_upsd_conf.stat.exists
  become: yes

- name: Template to /etc/nut/upsd.conf
  ansible.builtin.template:
    src: templates/upsd.conf.j2
    dest: /etc/nut/upsd.conf
    mode: '0644'
  become: yes

- name: Check if original nut.conf has been saved
  stat:
    path: /etc/nut/nut.conf.orig
  register: check_nut_conf

- name: Backup original nut.conf
  ansible.builtin.copy:
    src: /etc/nut/nut.conf
    dest: /etc/nut/nut.conf.orig
    remote_src: yes
    mode: '0644'
  when: not check_nut_conf.stat.exists
  become: yes

- name: Template to /etc/nut/nut.conf
  ansible.builtin.template:
    src: templates/nut.conf.j2
    dest: /etc/nut/nut.conf
    mode: '0644'
  become: yes

- name: Check if original upsd.users has been saved
  stat:
    path: /etc/nutupsd.users.orig
  register: check_upsd_users

- name: Backup original upsd.users
  ansible.builtin.copy:
    src: /etc/nut/upsd.users
    dest: /etc/nut/upsd.usersf.orig
    remote_src: yes
    mode: '0644'
  when: not check_upsd_users.stat.exists
  become: yes

- name: Template to /etc/nut/upsd.users
  ansible.builtin.template:
    src: templates/upsd.users.j2
    dest: /etc/nut/upsd.users
    mode: '0644'
  become: yes