---
- name: restart_sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: yes

- name: restart_fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: yes
