---
- name: Set Up Authorized key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', keyfile_location) }}"

- name: Disable root login over SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - restart_sshd
  become: yes

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify:
    - restart_sshd
  become: yes

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/id_ssh_rsa"

- name: Install apt fail2ban Packages
  apt: 
    name:
      - fail2ban
      - sendmail
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Configure jail.local File
  blockinfile:
    path: /etc/fail2ban/jail.local
    backup: yes
    create: yes
    block: |
      [sshd]
      enabled = true
      filter = sshd
      port = ssh
      banaction = iptables-multiport
      bantime = -1
      maxretry = 3
      logpath = %(sshd_log)s
      backend = %(sshd_backend)s
  become: yes
  notify:
    - restart_fail2ban

- name: Flush handlers
  meta: flush_handlers