---
- name: Update Cache and Upgrade all Packages
  register: updatesys
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  timeout: 600

- name: Download Plex server file
  get_url:
    url: "{{ plex_server_download_url }}"
    dest: /home/plexmediaserver.deb
    mode: '0440'

- name: Install Plex Server file
  apt: 
    deb: /home/plexmediaserver.deb
