---
- name: Configure RaspberryPi Nut Server
  hosts: piNutServers
  vars:
    apt_packages:
      - bat
      - neofetch
      - sshpass

  roles:
    - hardenSSH
    - installOhMyZSH
    - installgpakoszTmuxConf
    - passwordlessSudo
    - role: installNUT
      tags: nut

  tasks:
    - name: Install apt Packages
      become: yes
      apt:
        name: "{{ apt_packages }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Update Cache and Upgrade all Packages
      register: updatesys
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      timeout: 600

    - name: Display the last line of the previous task to check the stats
      debug:
        msg:  "{{updatesys.stdout_lines|last}}"

    - name: Insert/Update .zshrc File With TMUX at SSH Login
      blockinfile:
        path: /home/pi/.zshrc
        backup: yes
        block: |
          if [[ -n "$PS1" ]] && [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
            tmux attach-session -t ssh_tmux || tmux new-session -s ssh_tmux
          fi
