---
- name: Configure ProxMox Samba Containers
  hosts: plexContainers
  roles:
    - hardenSSH
    - setupPlex
  vars:
    apt_packages:
      - smbclient
      - cifs-utils

  tasks:
    - name: Update Cache and Upgrade all Packages
      register: updatesys
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      timeout: 600

    - name: Display the last line of the previous task to check the stats
      debug:
        msg:  "{{updatesys.stdout_lines|last}}"

    - name: Install apt Packages
      become: yes
      apt:
        name: "{{ apt_packages }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: check mountpoint exist
      ansible.builtin.file:
        path: "{{ samba_mount_point }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Mount network share
      ansible.posix.mount:
        src: "{{ samba_share_address }}"
        path: "{{ samba_mount_point }}"
        fstype: cifs
        opts: 'username={{ samba_user }},password={{ samba_passwd }}'
        state: mounted
