---
- name: Configure ProxMox Samba Containers
  hosts: sambaContainers
  roles:
    - hardenSSH
    - setupSamba

  tasks:
    - name: Update Cache and Upgrade all Packages
      register: updatesys
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      timeout: 600

    - name: Display the last line of the previous task to check the stats
      debug:
        msg:  "{{updatesys.stdout_lines|last}}"
